### PR TITLE
Add golang 1.13.8

### PR DESCRIPTION
**Pull request by dgassaway**

### CODE REVIEW

**Comment by dgassaway** [comment]
It's that time again

**Comment by benjyw** [comment]
@cosmicexplorer I thought we were now able to fetch go binaries directly from go's repository? Or at least have the ability to set that up?

**Comment by dgassaway** [comment]
ping for merge

**Comment by dgassaway** [comment]
Thanks for the merge! Forgot that it seems like this also has to be sync'd to S3

**Comment by benjyw** [comment]
I don't know how that's supposed to work... Anyone?

**Comment by dgassaway** [comment]
Per the repo readme someone with write permissions for the S3 bucket has to run the sync-s3.sh script with the merged changes as well as having run the new scripts the fetch the new go.tar.gz's.

**Comment by benjyw** [comment]
I'll give that a try.

**Comment by benjyw** [comment]
Is it just me, or is this repo impossible to clone due to all the huge binary files?

**Comment by benjyw** [comment]
OK repo sync'd, ran sync-s3.sh . It uploaded a lot of other stuff, not sure what's going on there.

**Comment by dgassaway** [comment]
Hmm. I can't access https://binaries.pantsbuild.org.s3.amazonaws.com/bin/go/linux/x86_64/1.13.8/go.tar.gz - this url format works for a prior version 1.12.7

**Comment by dgassaway** [comment]
I got unblocked on this internally, so no urgency here

**Comment by benjyw** [comment]
have asked on Slack for someone who knows more about this than I do to take a peek.

**Pull request merged**
