### PR TITLE
Add buildozer 0.4.5

### PR DESCRIPTION
**Pull request by michaelttran**
@wisechengyi @baroquebobcat @ity 

The Buildozer binary will support the ability to easily manipulate BUILD files. 

This follows up on https://github.com/pantsbuild/pants/pull/4882

### CODE REVIEW

**Comment by wisechengyi** [comment]
commented on https://github.com/pantsbuild/pants/pull/4921

**Comment by michaelttran** [comment]
@wisechengyi Added support for OSX binaries(10.11, 10.12, 10.13)

**Comment by 15Dkatz** [comment]
@wisechengyi Added support for a Linux binary.

**Comment by wisechengyi** [comment]
Why is the linux one `build-support/scripts/buildozer/linux/x86_64/4.4.0/buildozer` instead of 0.4.5? also it does not match https://github.com/bazelbuild/buildtools/releases/download/0.4.5/buildozer

**Comment by michaelttran** [comment]
@wisechengyi Updated Linux binary path to linux/x86_64/0.4.5/buildozer

**Pull request merged**
