### PR TITLE
Add OSX binary symlinks for 10.13

### PR DESCRIPTION
**Pull request by illicitonion**
dea601c3bea992a5c7886d3541ad2003cce1025d and
d8fe0801e0892c09e786caf5098d082efe89609e only added symlinks where the
type was already a file. If the target was already a smlink, nothing was
added.

This was generated with:

```bash
find $PWD/build-support/bin -wholename "*/mac/10.12/*" -type l | {
  while read binary
  do
    newbin=${binary/\/10.12\//\/10.13\/}

    binary=$(basename ${newbin})
    newdir=$(dirname ${newbin})
    version=$(basename ${newdir})

    rm -rf ${newdir}
    mkdir -p ${newdir}
    cd ${newdir}
    ln -s ../../10.12/${version}/${binary}
  done
}
```

exactly the same as d8fe0801e0892c09e786caf5098d082efe89609e but with
`-type l` instead of `-type f`.

### CODE REVIEW

**Comment by illicitonion** [comment]
@jsirois

**Comment by jsirois** [comment]
Ah nice, ty!

**Comment by jsirois** [comment]
Syncing these to s3 now...

**Comment by jsirois** [comment]
synched!

**Pull request merged**
