### PR TITLE
Switch to a workflow without committed binaries

### LINKED ISSUE #28: repo is exceeding soft size quota
Observed when merging #27.

See the email screen shot below:
pantsbuild-binaries-disk-full
In addition, this is backed up by https://help.github.com/articles/what-is-my-disk-quota/

Although we no longer rely on gh-pages rendering to create a site for `BinaryUtil`, it behooves us to switch to [LFS](https://help.github.com/articles/versioning-large-files/) since this is the 1st class mechanism github supports for storing large files.

### PR DESCRIPTION
**Pull request by stuhood**
This fixes #28 by ending (new) storage of binaries in this repository.

Before landing this change and switching to this workflow, we should enable versioning on the `binaries.pantsbuild.org` S3 bucket, and likely take one other defensive measure against loss of published binaries.

### CODE REVIEW

**Comment by cosmicexplorer** [comment]
I was thinking about lfs earlier today, but not as an auxiliary mechanism, so it seemed like we would easily overrun bandwidth limits if it was the primary way for users to fetch binary tools -- however, unless someone is intimately familiar with s3 versions, as a _private_ backup like @mateor just mentioned seems like it would be:

1. very cheap to store, [like $5 a month?!](https://help.github.com/articles/about-storage-and-bandwidth-usage/),
2. maintain the mapping of `pantsbuild/binaries SHA <-> binary content` without error,
3. also very cheap to recover from, assuming downloading anything from the LFS to incur "bandwidth" usage is probably only to restore from S3.

There's no reason this can't be done in addition to versioned S3, if that's just as easy to do, just some thoughts about `git-lfs` in isolation. I'm not opinionated about this, I really just like the idea of easy mapping from `git SHA <-> binary content`, mostly.

**Comment by mateor** [comment]
As mentioned by me elsewhere, we heavily extend binary_utils internally and we do pretty much as described immediately above.

* Primary source of truth is s3.
* Mirrored and served from http
* Mirrored to git-lfs as long term backup and OSS serving (*very* low bandwidth)
* Cache pants.bootstrap for CI

This is how I distribute source tarballs for docker images and RPMS, native libs, or any versioned blobs that doesn't have a Pants supported distribution protocol.

**Comment by stuhood** [comment]
Hey gang: I've updated the text to include a recommendation about where to locate the script. Please take another look.

**Comment by stuhood** [comment]
> Will ./sync-s3.sh do the right thing?

@benjyw : Yes: it only uploads new files.

**Pull request merged**
