### PR TITLE
Add npm scripts and binaries for mac

### PR DESCRIPTION
**Pull request by tejal29**
These will install npm modules for tasks 
1. LessC
2. RequireJs and
3. RTLCSS

The modules will be downloaded in node_modules directory where you run the scripts. 
Please copy the 
1. node_modules/less/bin/lessc  to appropriate platform specific dir.
2. node_modules/R2/bin/r2 to appropriate platform specific dir.
3. node_modules/requirejs/bin/r.js  to appropriate platform specific dir.

### CODE REVIEW

**Comment by tejal29** [comment]
@jsirois does this look good? Let me know if i should put up a req for this.
Also, i have a feeling, the lessc and require.js should be platform independent.

**Comment by jsirois** [comment]
Yeah - it seems to me the only binaries we should host are node and npm.  Pants can then use npm to do local installs of other tools in .pants.d (but probably with artifact caching turned on so they wind up in ~/.cache/pants/artifact_cache and are only ever installed once per version.

For the node and npm install you should be ensuring a static binary on linux and the build should rwally be local; ie: sudo is a big red flag.  I used `./configure --prefix` to do this, for example, for bison to support building thrift on OSX's with too-old a bison, but wanting to avoid installing bison on the builder's machine.  See here: https://github.com/pantsbuild/binaries/blob/gh-pages/build-thrift-0.9.2.sh#L3

**Comment by tejal29** [comment]
@jsirois can we merge this in?

**Comment by jsirois** [comment]
I'd prefer not as per my comments above.  The build script does scary things as root, etc.  Can you respond to that?

**Comment by jsirois** [comment]
oh... you did do changes - just a sec.

**Comment by jsirois** [comment]
@tejal29 - so this departs from how binaries works to-date.  Do you need everything in those tarballs or just bin/node and bin/npm?

**Comment by tejal29** [comment]
No, the way node works, it needs everything in lib folder.

The binary for  npm bin/npm is nothing but a file pointer to lib/node_modules/npm/bin/npm-cli.js

`npm install <module>` actually runs sources froms lib folder. So i need everything in those tarballs.

**Comment by jsirois** [comment]
Ok then, I'm happy with this.  I'll squash this in as 1 commit and publish presently.

**Comment by tejal29** [comment]
Thanks a lot!

**Comment by jsirois** [comment]
OK - squashed in @ https://github.com/pantsbuild/binaries/commit/ea277381173b04ee4780c3c26fe7d50d7b94e73b and synced up to bintray.

**Pull request closed without merging**
